[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/L_LogicLab
GameDefaultMap=/Game/Maps/L_Tutorial
GlobalDefaultGameMode=/Script/Tripothon.TripoGameMode

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.DefaultFeature.AutoExposure=False
r.AllowStaticLighting=False
r.GenerateMeshDistanceFields=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/Engine.Engine]
bSmoothFrameRate=False

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=FB1B832F411C259E996140873FACE349
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


; Use the filesystem DDC when the local Zen service is unavailable.
[InstalledDerivedDataBackendGraph]
Hierarchy=(Type=Hierarchical, Inner=Pak, Inner=CompressedPak, Inner=EnginePak, Inner=EnterprisePak, Inner=Local, Inner=ZenShared, Inner=Shared, Inner=Cloud)
Local=(Type=FileSystem, DeleteOnly=false, UnusedFileAge=34, Path="%ENGINEVERSIONAGNOSTICUSERDIR%DerivedDataCache", EnvPathOverride=UE-LocalDataCachePath, EditorOverrideSetting=LocalDerivedDataCache)
